name: IKE Artifactory Ruby tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.6', '2.7', '3.0']
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: Test the gem
        run: |
          gem install bundler
          bundler install
          bundle exec rake test
      - run: echo "ğŸ This job's status is ${{ job.status }}."

  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - run: echo "Building gem"
      - name: Build the gem
        run: |
          rm -f *.gem
          gem build $(ls *.gemspec)
      - run: echo "Pushing the gem to rubygems.org"
      - name: Push the gem 
        env:
          RUBYGEMS_API_TOKEN: ${{ secrets.RUBYGEMS_API_TOKEN }}
        run: |
          mkdir -p ~/.gem
          echo -e "---\n:rubygems_api_key: $RUBYGEMS_API_TOKEN" >> ~/.gem/credentials
          chmod 0600 ~/.gem/credentials
          gem push $(ls *.gem)
 